remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Vibe coding
description: Vibe coding documentation
show_downloads: true

github:
  repository_url: ''

show_footer: false
